name: Build and Upload Artifact

on:
  push:
    branches:
      - main  # replace with your default branch if not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21  # replace with your Go version

    - name: Build
      run: go build -v ./...

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ./tailtrail 